---
- name: Install all programs
  hosts: all
  become: yes

  tasks:
  

  - name: Update apt packeage
    become: true
    apt:
      update_cache: yes
  

  - name: Install required packages
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
      state: latest
      update_cache: yes



  - name: Add Docker GPG apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest

  - name: Install Docker Module for Python
    pip:
      name: docker



  - name: Adding existing users to group
    user:
      name: '{{ item }}'
      groups: docker
      append: yes
    with_items:
      - jenkins
      - '{{ USER }}'




  - name: Configure ufw rules
    ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.protocol }}
    with_items:
      - { rule: 'allow', port: '8080', protocol: 'tcp' }
      - { rule: 'allow', port: '8090', protocol: 'tcp' }
      - { rule: 'allow', port: '80', protocol: 'tcp' }
      - { rule: 'allow', port: '22', protocol: 'tcp' }

  - name: Allow OpenSSH
    ufw: rule=allow name=OpenSSH

  - name: Enable ufw logging
    ufw: logging=on

  - name: Enable ufw
    ufw: state=enabled policy=allow




  - name: Restart Docker
    service: name=docker state=restarted
  
  
  
  
  - name: Install Sshpass
    apt: pkg=sshpass state=latest

 
  

  - name: Reboot
    reboot:
      reboot_timeout: 3600
